export * from "./navigation/navigation.route";
export * from "./home/home.route";
export * from "./sign-in/sign-in.route";
export * from "./sign-up/sign-up.route";
export * from './book/book.route'
export * from './book-details/book-details.route'
export * from './dashboard/dashboard.route'
export * from './accessibility/accessibility.route'
export * from './privacy/privacy.route'